[tool.poetry]
name = "goga"
version = "0.1.0"
description = ""
authors = ["n.vladimirov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
